version: "3"

volumes:
  ztncui:
  zt1:

services:
  ztncui:
    image: keynetworks/ztncui
    container_name: ztncui
    environment:
      - USER_UID=998 #adjust to your system
      - USER_GID=100 #adjust to your system
      - NODE_ENV=production
      - HTTPS_PORT=3443
      - ZTNCUI_PASSWD=password  #change this
      - MYDOMAIN=zt.yourdomain.com #change this to the domain you want to use for the controller
      - MYADDR=12.34.56.78 #this is optional. if you use it, this is the public IP your ISP gave you
    volumes:
      - "./zt/ztncui:/opt/key-networks/ztncui/etc"
      - "./zt/zt1:/var/lib/zerotier-one"
    ports:
      - 9000:3443 #dashboard port
      - 3180:3180

  nginx:
    image: nginx:latest
    container_name: zt-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./ng/:/etc/nginx/conf.d/"
      - "./ng/ssl:/etc/ssl"  
